### ISSUE TITLE
LootTableIdCondition::test always returns false

### ISSUE THREAD

**Issue by ochotonida** [Fabricators-of-Create/Porting-Lib#57]
LootTableIdCondition::test always returns false, because it incorrectly compares the target loot table with porting_lib:unknown_loot_table instead of the queried loot table.

I tried implementing the condition myself using LootContextExtensions::getQueriedLootTableId, but this method consistently returns porting_lib:unknown_loot_table, which seems to be caused by LootTableExtensions::setLootTableId not being called anywhere.

**Comment by ochotonida** [comment]
This issue doesn't seem to be fixed yet, although perhaps my explanation of what causes it was a bit unclear.

Updating the condition such that it uses `getQueriedLootTableId` only partly fixes the problem, because `getQueriedLootTableId` isn't working as intended either.

**Comment by TropheusJ** [comment]
hopefully fixed in latest commit, conditions were checked before queried ID was set

**Comment by ochotonida** [comment]
It's still not working, the loot table is already null when it's passed to `setQueriedLootTableId`

**Comment by TropheusJ** [comment]
ah.
![image](https://github.com/Fabricators-of-Create/Porting-Lib/assets/60247969/159ec50e-afd2-482a-8f48-565dd3cdbd80)

**Comment by TropheusJ** [comment]
fixed that, should be good now

**Comment by ochotonida** [comment]
This works now, thanks!
